> jupyter 使用 toc 扩展进行编辑,建议开启,比较方便阅读和查找

## 收集
### / import lib
### / load df

In [40]:
# import libs
import pandas as pd
import numpy as np

import pprint  as pp

In [41]:
# load df
## read_jason 有很多参数,可以参考官方文档
## 此处要加 lines=True
tweetdf = pd.read_json('tweet_json.txt',lines=True)
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html

### / copy df

In [110]:
## df copy for assesment
tweetclean = tweetdf.copy()

### / functions
#### // check_sample(df)

In [44]:
# build function (base on solution2)
def check_sample(df):
    sample = df.sample(1)
    print('----checking sample index: {}'.format(sample.index[0]))
    ### sometimes pp is uncaptible with .format
    i = 1
    for (colname, coldata) in sample.iteritems():
        print('\n- columns #{} : {:-<8}'.format(i,colname))
        print(coldata.values)
        i += 1
    pp.pprint('----checking complete----')

# archive test
## solutions1 (col loop pass)
'''
sample = tweetdf.sample()
p('----checking sample index: {:-<8}'.format(sample.index[0]))

i = 1
for col in list(tweetdf.columns):
    print('\n- columns check {} : {:-<8}'.format(i,col))
    print(sample[col].values)
    i+=1
## 参考 https://thispointer.com/pandas-loop-or-iterate-over-all-or-certain-columns-of-a-dataframe/
'''

## solutuion2 (iteritem pass)
'''
sample = tweetdf.sample()
p('----checking sample index: {:-<8}'.format(sample.index[0]))


for (colname, coldata) in sample.iteritems():
    print('\n- columns check {} : {:-<8}'.format(i,colname))
    print(coldata.values)
    i += 1
''';

#### // check_info(df,list)

In [47]:
# build function
def check_info(df,list):
    c = 1
    for i in list:
        print(('\n- columns #{} : {:-<8}'.format(c,i)))
        print((df[i].value_counts().nlargest(5)))
        ### nlargest 非常好用
        c += 1
    pp.pprint('----checking complete----')

#### // check_detail(df,list)

In [119]:
# build function
def check_detail(df,list):
    sampe = df.sample(1)
    c = 1
    for i in list:
        print(('\n- columns #{} : {:-<8}'.format(c,i)))
        pp.pprint(df[i].iloc[0])
        c += 1
        ## 使用 pprint 优化 dict 显示

#### // drop_column

In [51]:
## build fuction
def drop_column(df,list):
    ## proceed
    dflen = len(df.columns)
    df.drop(list,axis=1,inplace=True)
    ### 在函数中要用 inplace=True 而不是赋值来作用于df
    ## check
    print('---- proceding ----')
    print('- drop {} columns: {} '.format(len(list), list))
    print('- remain {} columns'.format(len(df.columns)))
    print('- success : {}'.format(len(list) + len(df.columns) == dflen))

## 评估
### / 质量
#### // check1 - init drop

In [52]:
# check1 
## snip all columns
check_sample(tweetdf)

----checking sample index: 1829

- columns #1 : contributors
[nan]

- columns #2 : coordinates
[nan]

- columns #3 : created_at
['2015-12-13T21:07:04.000000000']

- columns #4 : display_text_range
[list([0, 61])]

- columns #5 : entities
[{'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 676146336014667776, 'id_str': '676146336014667776', 'indices': [38, 61], 'media_url': 'http://pbs.twimg.com/media/CWIngp5WEAAJOy3.jpg', 'media_url_https': 'https://pbs.twimg.com/media/CWIngp5WEAAJOy3.jpg', 'url': 'https://t.co/lmQRrNxaQu', 'display_url': 'pic.twitter.com/lmQRrNxaQu', 'expanded_url': 'https://twitter.com/dog_rates/status/676146341966438401/photo/1', 'type': 'photo', 'sizes': {'small': {'w': 680, 'h': 510, 'resize': 'fit'}, 'medium': {'w': 1024, 'h': 768, 'resize': 'fit'}, 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'large': {'w': 1024, 'h': 768, 'resize': 'fit'}}}]}]

- columns #6 : extended_entities
[{'media': [{'id': 676146336014667776, 'id_str': '676146336014667776', 'indices': [38, 61], 'media_url': 'http://pbs.twimg.com/media/CWIngp5WEAAJOy3.jpg', 'media_url_https': 'https://pbs.twimg.com/media/CWIngp5WEAAJOy3.jpg', 'url': 'https://t.co/lmQRrNxaQu', 'display_url': 'pic.twitter.com/lmQRrNxaQu', 'expanded_url': 'https://twitter.com/dog_rates/status/676146341966438401/photo/1', 'type': 'photo', 'sizes': {'small': {'w': 680, 'h': 510, 'resize': 'fit'}, 'medium': {'w': 1024, 'h': 768, 'resize': 'fit'}, 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'large': {'w': 1024, 'h': 768, 'resize': 'fit'}}}]}]

- columns #7 : favorite_count
[2068]

- columns #8 : favorited
[False]

- columns #9 : full_text
['This is Bert. He likes flowers. 10/10 https://t.co/lmQRrNxaQu']

- columns #10 : geo-----
[nan]

- columns #11 : id------
[676146341966438401]

- columns #12 : id_str--
[676146341966438400]

- columns #13 : in_reply_to_screen_name
[None]

- columns #14 : in_reply_to_status_id
[nan]

- columns #15 : in_reply_to_status_id_str
[nan]

- columns #16 : in_reply_to_user_id
[nan]

- columns #17 : in_reply_to_user_id_str
[nan]

- columns #18 : is_quote_status
[False]

- columns #19 : lang----
['en']

- columns #20 : place---
[None]

- columns #21 : possibly_sensitive
[0.]

- columns #22 : possibly_sensitive_appealable
[0.]

- columns #23 : quoted_status
[nan]

- columns #24 : quoted_status_id
[nan]

- columns #25 : quoted_status_id_str
[nan]

- columns #26 : retweet_count
[739]

- columns #27 : retweeted
[False]

- columns #28 : retweeted_status
[nan]

- columns #29 : source--
['<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>']

- columns #30 : truncated
[False]

- columns #31 : user----
[{'id': 4196983835, 'id_str': '4196983835', 'name': 'SpookyWeRateDogs™', 'screen_name': 'dog_rates', 'location': 'MERCH↴  DM DOGS. WE WILL RATE', 'description': 'Only Legit Source for Professional Dog Ratings STORE: @ShopWeRateDogs | IG, FB & SC: WeRateDogs | MOBILE APP: @GoodDogsGame Business: dogratingtwitter@gmail.com', 'url': 'https://t.co/N7sNNHAEXS', 'entities': {'url': {'urls': [{'url': 'https://t.co/N7sNNHAEXS', 'expanded_url': 'http://weratedogs.com', 'display_url': 'weratedogs.com', 'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 3768931, 'friends_count': 107, 'listed_count': 3325, 'created_at': 'Sun Nov 15 21:41:29 +0000 2015', 'favourites_count': 120161, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True, 'verified': True, 'statuses_count': 5749, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': '000000', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/914581071265755136/2h5uFpwU_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/914581071265755136/2h5uFpwU_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/4196983835/1506888628', 'profile_link_color': 'F5ABB5', 'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000', 'profile_use_background_image': False, 'has_extended_profile': True, 'default_profile': False, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'}]
'----checking complete----'

In [53]:
## snip info
tweetdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2352 entries, 0 to 2351
Data columns (total 31 columns):
contributors                     0 non-null float64
coordinates                      0 non-null float64
created_at                       2352 non-null datetime64[ns]
display_text_range               2352 non-null object
entities                         2352 non-null object
extended_entities                2073 non-null object
favorite_count                   2352 non-null int64
favorited                        2352 non-null bool
full_text                        2352 non-null object
geo                              0 non-null float64
id                               2352 non-null int64
id_str                           2352 non-null int64
in_reply_to_screen_name          78 non-null object
in_reply_to_status_id            78 non-null float64
in_reply_to_status_id_str        78 non-null float64
in_reply_to_user_id              78 non-null float64
in_reply_to_user_id_str          78 non-null float64
is_quote_status                  2352 non-null bool
lang                             2352 non-null object
place                            1 non-null object
possibly_sensitive               2211 non-null float64
possibly_sensitive_appealable    2211 non-null float64
quoted_status                    28 non-null object
quoted_status_id                 29 non-null float64
quoted_status_id_str             29 non-null float64
retweet_count                    2352 non-null int64
retweeted                        2352 non-null bool
retweeted_status                 177 non-null object
source                           2352 non-null object
truncated                        2352 non-null bool
user                             2352 non-null object
dtypes: bool(4), datetime64[ns](1), float64(11), int64(4), object(11)
memory usage: 505.4+ KB

In [54]:
## define drop list
droplist1 = ['contributors','coordinates','geo','place','id_str','in_reply_to_status_id_str','in_reply_to_user_id_str','quoted_status_id_str']

In [56]:
## droplist1
droplist1 = ['contributors','coordinates','geo','place','id_str','in_reply_to_status_id_str','in_reply_to_user_id_str','quoted_status_id_str']

In [111]:
## drop1 excute
drop_column(tweetclean,droplist1)

---- proceding ----
- drop 8 columns: ['contributors', 'coordinates', 'geo', 'place', 'id_str', 'in_reply_to_status_id_str', 'in_reply_to_user_id_str', 'quoted_status_id_str']
- remain 23 columns
- success : True

#### // check2 - inspect drop

In [84]:
# check2
## snip remained columns
check_sample(tweetclean)

----checking sample index: 1714

- columns #1 : created_at
['2015-12-25T00:00:11.000000000']

- columns #2 : display_text_range
[list([0, 94])]

- columns #3 : entities
[{'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 680176161213779968, 'id_str': '680176161213779968', 'indices': [71, 94], 'media_url': 'http://pbs.twimg.com/media/CXB4nWnWEAAhLTX.jpg', 'media_url_https': 'https://pbs.twimg.com/media/CXB4nWnWEAAhLTX.jpg', 'url': 'https://t.co/NhXo67K6yt', 'display_url': 'pic.twitter.com/NhXo67K6yt', 'expanded_url': 'https://twitter.com/dog_rates/status/680176173301628928/photo/1', 'type': 'photo', 'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'medium': {'w': 768, 'h': 1024, 'resize': 'fit'}, 'large': {'w': 768, 'h': 1024, 'resize': 'fit'}, 'small': {'w': 510, 'h': 680, 'resize': 'fit'}}}]}]

- columns #4 : extended_entities
[{'media': [{'id': 680176161213779968, 'id_str': '680176161213779968', 'indices': [71, 94], 'media_url': 'http://pbs.twimg.com/media/CXB4nWnWEAAhLTX.jpg', 'media_url_https': 'https://pbs.twimg.com/media/CXB4nWnWEAAhLTX.jpg', 'url': 'https://t.co/NhXo67K6yt', 'display_url': 'pic.twitter.com/NhXo67K6yt', 'expanded_url': 'https://twitter.com/dog_rates/status/680176173301628928/photo/1', 'type': 'photo', 'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'medium': {'w': 768, 'h': 1024, 'resize': 'fit'}, 'large': {'w': 768, 'h': 1024, 'resize': 'fit'}, 'small': {'w': 510, 'h': 680, 'resize': 'fit'}}}]}]

- columns #5 : favorite_count
[4252]

- columns #6 : full_text
['This pupper is patiently waiting to scare the shit out of Santa. 10/10 https://t.co/NhXo67K6yt']

- columns #7 : id------
[680176173301628928]

- columns #8 : quoted_status
[nan]

- columns #9 : retweet_count
[1753]

- columns #10 : retweeted_status
[nan]

- columns #11 : source--
['<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>']

- columns #12 : user----
[{'id': 4196983835, 'id_str': '4196983835', 'name': 'SpookyWeRateDogs™', 'screen_name': 'dog_rates', 'location': 'MERCH↴  DM DOGS. WE WILL RATE', 'description': 'Only Legit Source for Professional Dog Ratings STORE: @ShopWeRateDogs | IG, FB & SC: WeRateDogs | MOBILE APP: @GoodDogsGame Business: dogratingtwitter@gmail.com', 'url': 'https://t.co/N7sNNHAEXS', 'entities': {'url': {'urls': [{'url': 'https://t.co/N7sNNHAEXS', 'expanded_url': 'http://weratedogs.com', 'display_url': 'weratedogs.com', 'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 3768907, 'friends_count': 107, 'listed_count': 3315, 'created_at': 'Sun Nov 15 21:41:29 +0000 2015', 'favourites_count': 120161, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True, 'verified': True, 'statuses_count': 5749, 'lang': 'en', 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': '000000', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/914581071265755136/2h5uFpwU_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/914581071265755136/2h5uFpwU_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/4196983835/1506888628', 'profile_link_color': 'F5ABB5', 'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000', 'profile_use_background_image': False, 'has_extended_profile': True, 'default_profile': False, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none'}]
'----checking complete----'

In [98]:
## define inspect list
inslist1 = ['favorited','in_reply_to_screen_name','in_reply_to_status_id','in_reply_to_user_id','is_quote_status','lang','possibly_sensitive','possibly_sensitive_appealable','quoted_status_id','retweeted','truncated']
### special action below is altered

In [61]:
## inspect1 excute
check_info(tweetclean,inslist1)

- columns #1 : favorited
False    2352
Name: favorited, dtype: int64

- columns #2 : in_reply_to_screen_name
dog_rates       47
markhoppus       2
imgur            1
TheEllenShow     1
s8n              1
Name: in_reply_to_screen_name, dtype: int64

- columns #3 : in_reply_to_status_id
6.671522e+17    2
8.562860e+17    1
8.131273e+17    1
6.754971e+17    1
6.827884e+17    1
Name: in_reply_to_status_id, dtype: int64

- columns #4 : in_reply_to_user_id
4.196984e+09    47
2.195506e+07     2
7.305050e+17     1
2.916630e+07     1
3.105441e+09     1
Name: in_reply_to_user_id, dtype: int64

- columns #5 : is_quote_status
False    2321
True       31
Name: is_quote_status, dtype: int64

- columns #6 : lang----
en     2334
und       7
in        3
nl        3
ro        1
Name: lang, dtype: int64

- columns #7 : possibly_sensitive
0.0    2211
Name: possibly_sensitive, dtype: int64

- columns #8 : possibly_sensitive_appealable
0.0    2211
Name: possibly_sensitive_appealable, dtype: int64

- columns #9 : quoted_status_id
8.340867e+17    1
8.413114e+17    1
7.061659e+17    1
8.860534e+17    1
8.464848e+17    1
Name: quoted_status_id, dtype: int64

- columns #10 : retweeted
False    2352
Name: retweeted, dtype: int64

- columns #11 : truncated
False    2352
Name: truncated, dtype: int64
'----checking complete----'

In [62]:
## special1 
### quoted_status is a dict, move it to detlist
### check values (almost is null)
tweetclean.quoted_status.isnull().value_counts()

True     2324
False      28
Name: quoted_status, dtype: int64

In [63]:
### many NaN
### check a sample
tweetclean[tweetclean.quoted_status.notnull()].sample(1).quoted_status.iloc[0]
### status is some extra info abou a forward

{'created_at': 'Mon Jun 12 23:49:34 +0000 2017',
 'id': 874413398133547008,
 'id_str': '874413398133547008',
 'full_text': 'So this is why my damn "delivered by 3pm" packages don\'t arrive until 7... https://t.co/8bK5fRSK4W',
 'truncated': False,
 'display_text_range': [0, 74],
 'entities': {'hashtags': [],
  'symbols': [],
  'user_mentions': [],
  'urls': [],
  'media': [{'id': 874413321549631488,
    'id_str': '874413321549631488',
    'indices': [75, 98],
    'media_url': 'http://pbs.twimg.com/ext_tw_video_thumb/874413321549631488/pu/img/Vvl1-BABjrCGgFwA.jpg',
    'media_url_https': 'https://pbs.twimg.com/ext_tw_video_thumb/874413321549631488/pu/img/Vvl1-BABjrCGgFwA.jpg',
    'url': 'https://t.co/8bK5fRSK4W',
    'display_url': 'pic.twitter.com/8bK5fRSK4W',
    'expanded_url': 'https://twitter.com/DrBoondoc/status/874413398133547008/video/1',
    'type': 'photo',
    'sizes': {'small': {'w': 340, 'h': 604, 'resize': 'fit'},
     'large': {'w': 720, 'h': 1280, 'resize': 'fit'},
     'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
     'medium': {'w': 600, 'h': 1067, 'resize': 'fit'}}}]},
 'extended_entities': {'media': [{'id': 874413321549631488,
    'id_str': '874413321549631488',
    'indices': [75, 98],
    'media_url': 'http://pbs.twimg.com/ext_tw_video_thumb/874413321549631488/pu/img/Vvl1-BABjrCGgFwA.jpg',
    'media_url_https': 'https://pbs.twimg.com/ext_tw_video_thumb/874413321549631488/pu/img/Vvl1-BABjrCGgFwA.jpg',
    'url': 'https://t.co/8bK5fRSK4W',
    'display_url': 'pic.twitter.com/8bK5fRSK4W',
    'expanded_url': 'https://twitter.com/DrBoondoc/status/874413398133547008/video/1',
    'type': 'video',
    'sizes': {'small': {'w': 340, 'h': 604, 'resize': 'fit'},
     'large': {'w': 720, 'h': 1280, 'resize': 'fit'},
     'thumb': {'w': 150, 'h': 150, 'resize': 'crop'},
     'medium': {'w': 600, 'h': 1067, 'resize': 'fit'}},
    'video_info': {'aspect_ratio': [9, 16],
     'duration_millis': 11600,
     'variants': [{'bitrate': 320000,
       'content_type': 'video/mp4',
       'url': 'https://video.twimg.com/ext_tw_video/874413321549631488/pu/vid/180x320/AikxdBgb7tS_srdy.mp4'},
      {'bitrate': 2176000,
       'content_type': 'video/mp4',
       'url': 'https://video.twimg.com/ext_tw_video/874413321549631488/pu/vid/720x1280/k_aMBt4Fk5ixdRLL.mp4'},
      {'content_type': 'application/x-mpegURL',
       'url': 'https://video.twimg.com/ext_tw_video/874413321549631488/pu/pl/3bG-0yJtywavfmYz.m3u8'},
      {'bitrate': 832000,
       'content_type': 'video/mp4',
       'url': 'https://video.twimg.com/ext_tw_video/874413321549631488/pu/vid/360x640/_3DZesO10cg_jPkm.mp4'}]},
    'additional_media_info': {'monetizable': False}}]},
 'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
 'in_reply_to_status_id': None,
 'in_reply_to_status_id_str': None,
 'in_reply_to_user_id': None,
 'in_reply_to_user_id_str': None,
 'in_reply_to_screen_name': None,
 'user': {'id': 21357526,
  'id_str': '21357526',
  'name': 'Raud E. Coyote',
  'screen_name': 'DrBoondoc',
  'location': 'The Isle of Dr Morehoes',
  'description': 'ignorant and insensitive. professional heathen. geektraordinaire. Unrepentantly ridiculous. inflated sense of self aggrandizement and a propensity to hyperbole.',
  'url': None,
  'entities': {'description': {'urls': []}},
  'protected': False,
  'followers_count': 391,
  'friends_count': 154,
  'listed_count': 20,
  'created_at': 'Fri Feb 20 00:32:04 +0000 2009',
  'favourites_count': 397,
  'utc_offset': -14400,
  'time_zone': 'Eastern Time (US & Canada)',
  'geo_enabled': True,
  'verified': False,
  'statuses_count': 49799,
  'lang': 'en',
  'contributors_enabled': False,
  'is_translator': False,
  'is_translation_enabled': False,
  'profile_background_color': 'FBF7ED',
  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
  'profile_background_tile': False,
  'profile_image_url': 'http://pbs.twimg.com/profile_images/766417192007139328/Gzg9atCH_normal.jpg',
  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/766417192007139328/Gzg9atCH_normal.jpg',
  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/21357526/1375303436',
  'profile_link_color': '0084B4',
  'profile_sidebar_border_color': 'FFC157',
  'profile_sidebar_fill_color': '303A41',
  'profile_text_color': '000000',
  'profile_use_background_image': False,
  'has_extended_profile': False,
  'default_profile': False,
  'default_profile_image': False,
  'following': False,
  'follow_request_sent': False,
  'notifications': False,
  'translator_type': 'none'},
 'geo': None,
 'coordinates': None,
 'place': None,
 'contributors': None,
 'is_quote_status': False,
 'retweet_count': 30504,
 'favorite_count': 79798,
 'favorited': False,
 'retweeted': False,
 'possibly_sensitive': False,
 'possibly_sensitive_appealable': False,
 'lang': 'en'}

In [64]:
# special2
### in_reply_to_screen_name have value dog_rates for 47 times
tweetclean.query('in_reply_to_screen_name == "dog_rates"')

,created_at,display_text_range,entities,extended_entities,favorite_count,favorited,full_text,id,in_reply_to_screen_name,in_reply_to_status_id,...,possibly_sensitive,possibly_sensitive_appealable,quoted_status,quoted_status_id,retweet_count,retweeted,retweeted_status,source,truncated,user
147,2017-05-12 17:12:53,"[0, 139]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 863079538779013120, 'id_str'...",9068,False,Ladies and gentlemen... I found Pipsy. He may ...,863079547188785154,dog_rates,6.671522e+17,...,0.0,0.0,NaN,NaN,1188,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
181,2017-04-24 15:13:52,"[0, 112]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 856526604033556482, 'id_str'...",12412,False,"THIS IS CHARLIE, MARK. HE DID JUST WANT TO SAY...",856526610513747968,dog_rates,8.558181e+17,...,0.0,0.0,NaN,NaN,2053,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
225,2017-04-01 16:41:12,"[0, 135]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,8799,False,Jerry just apuppologized to me. He said there ...,848213670039564288,dog_rates,8.482121e+17,...,NaN,NaN,NaN,NaN,825,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
231,2017-03-31 01:11:22,"[18, 79]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,7523,False,.@breaannanicolee PUPDATE: Cannon has a heart ...,847617282490613760,dog_rates,8.476062e+17,...,NaN,NaN,NaN,NaN,462,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
248,2017-03-23 18:29:57,"[0, 115]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 844979535204429824, 'id_str'...",14678,False,PUPDATE: I'm proud to announce that Toby is 23...,844979544864018432,dog_rates,7.590995e+17,...,0.0,0.0,NaN,NaN,2891,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
384,2017-02-01 01:11:25,"[0, 69]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,5617,False,"I was going to do 007/10, but the joke wasn't ...",826598799820865537,dog_rates,8.265984e+17,...,NaN,NaN,NaN,NaN,292,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
495,2016-12-25 21:12:41,"[0, 131]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,4949,False,I've been informed by multiple sources that th...,813130366689148928,dog_rates,8.131273e+17,...,NaN,NaN,NaN,NaN,511,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
510,2016-12-21 19:01:02,"[0, 136]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,6189,False,PUPDATE: I've been informed that Augie was act...,811647686436880384,dog_rates,8.116272e+17,...,NaN,NaN,NaN,NaN,866,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
562,2016-11-25 21:37:47,"[0, 45]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 802265039247904768, 'id_str'...",7011,False,"Like doggo, like pupper version 2. Both 11/10 ...",802265048156610565,dog_rates,7.331095e+17,...,0.0,0.0,NaN,NaN,1568,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
839,2016-08-19 19:14:16,"[0, 139]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,2862,False,His name is Charley and he already has a new s...,766714921925144576,dog_rates,7.667118e+17,...,NaN,NaN,NaN,NaN,435,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1001,2016-06-28 04:42:46,"[0, 132]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,1510,False,Other pupper asked not to have his identity sh...,747651430853525504,dog_rates,7.476487e+17,...,NaN,NaN,NaN,NaN,177,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1012,2016-06-26 03:22:31,"[0, 95]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 746906454414790656, 'id_str'...",3158,False,"PUPDATE: can't see any. Even if I could, I cou...",746906459439529985,dog_rates,7.468859e+17,...,0.0,0.0,NaN,NaN,334,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1014,2016-06-25 21:34:37,"[0, 38]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 746818901464453120, 'id_str'...",5785,False,Guys... Dog Jesus 2.0\n13/10 buoyant af https:...,746818907684614144,dog_rates,6.914169e+17,...,0.0,0.0,NaN,NaN,1933,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1123,2016-05-10 01:00:58,"[0, 43]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 729838572744912896, 'id_str'...",1849,False,"""Challenge completed"" \n(pupgraded to 12/10) h...",729838605770891264,dog_rates,7.291135e+17,...,0.0,0.0,NaN,NaN,426,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1326,2016-03-04 16:06:36,"[0, 68]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 705786528321044482, 'id_str'...",2125,False,"Seriously, add us 🐶 11/10 for sad wet pupper h...",705786532653883392,dog_rates,7.032559e+17,...,0.0,0.0,NaN,NaN,592,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1335,2016-03-02 03:30:25,"[0, 53]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 704871447097905152, 'id_str'...",4564,False,I found a forest Pipsy. 12/10 https://t.co/mIQ...,704871453724954624,dog_rates,6.671522e+17,...,0.0,0.0,NaN,NaN,1244,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1352,2016-02-27 03:42:44,"[0, 135]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 703424980705538048, 'id_str'...",4153,False,Really guys? Again? I know this is a rare Alba...,703425003149250560,dog_rates,7.030419e+17,...,0.0,0.0,NaN,NaN,1554,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1442,2016-02-08 00:27:39,"[0, 101]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,1334,False,After reading the comments I may have overesti...,696490539101908992,dog_rates,6.964887e+17,...,NaN,NaN,NaN,NaN,169,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1448,2016-02-06 00:35:13,"[0, 101]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 695767665437233153, 'id_str'...",2047,False,If you are aware of who is making these please...,695767669421768709,dog_rates,6.753494e+17,...,0.0,0.0,NaN,NaN,850,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1460,2016-02-02 03:08:26,"[0, 135]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 694356670072373248, 'id_str'...",1643,False,This pupper only appears through the hole of a...,694356675654983680,dog_rates,6.706684e+17,...,0.0,0.0,NaN,NaN,325,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1470,2016-01-31 03:57:23,"[0, 135]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,1468,False,BREAKING PUPDATE: I've just been notified that...,693644216740769793,dog_rates,6.936422e+17,...,NaN,NaN,NaN,NaN,149,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1493,2016-01-27 19:05:49,"[0, 103]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,1613,False,PUPDATE: just noticed this dog has some extra ...,692423280028966913,dog_rates,6.924173e+17,...,NaN,NaN,NaN,NaN,263,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1497,2016-01-27 00:31:15,"[0, 108]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 692142771344400384, 'id_str'...",1788,False,These are some pictures of Teddy that further ...,692142790915014657,dog_rates,6.920419e+17,...,0.0,0.0,NaN,NaN,437,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1594,2016-01-10 04:04:10,"[0, 136]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,1271,False,Yes I do realize a rating of 4/20 would've bee...,686035780142297088,dog_rates,6.860340e+17,...,NaN,NaN,NaN,NaN,138,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1601,2016-01-09 04:34:45,"[0, 130]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,2219,False,Jack deserves another round of applause. If yo...,685681090388975616,dog_rates,6.855479e+17,...,NaN,NaN,NaN,NaN,143,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1614,2016-01-07 05:28:35,"[0, 140]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,2509,False,"For those who claim this is a goat, u are wron...",684969860808454144,dog_rates,6.849598e+17,...,NaN,NaN,NaN,NaN,435,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1626,2016-01-06 00:54:18,"[0, 120]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 684538367950872576, 'id_str'...",2902,False,"After watching this video, we've determined th...",684538444857667585,dog_rates,6.844811e+17,...,0.0,0.0,NaN,NaN,1082,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1630,2016-01-05 04:11:44,"[0, 126]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 684225739852492800, 'id_str'...",1361,False,"Two sneaky puppers were not initially seen, mo...",684225744407494656,dog_rates,6.842229e+17,...,0.0,0.0,NaN,NaN,239,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1659,2016-01-01 06:22:03,"[0, 139]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,1941,False,"I'm aware that I could've said 20/16, but here...",682808988178739200,dog_rates,6.827884e+17,...,NaN,NaN,NaN,NaN,209,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1685,2015-12-28 05:07:27,"[0, 106]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,1797,False,I've been told there's a slight possibility he...,681340665377193984,dog_rates,6.813394e+17,...,NaN,NaN,NaN,NaN,312,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1770,2015-12-19 01:25:31,"[0, 92]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,2085,False,After getting lost in Reese's eyes for several...,678023323247357953,dog_rates,6.780211e+17,...,NaN,NaN,NaN,NaN,438,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1815,2015-12-15 02:32:17,"[0, 110]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,992,False,After some outrage from the crowd. Bubbles is ...,676590572941893632,dog_rates,6.765883e+17,...,NaN,NaN,NaN,NaN,142,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1838,2015-12-13 02:51:51,"[0, 144]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 675870715636224001, 'id_str'...",1771,False,&amp; this is Yoshi. Another world record cont...,675870721063669760,dog_rates,6.757073e+17,...,0.0,0.0,NaN,NaN,628,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1840,2015-12-13 01:25:37,"[0, 111]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,1021,False,This dog is being demoted to a 9/10 for not we...,675849018447167488,dog_rates,6.758457e+17,...,NaN,NaN,NaN,NaN,170,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1848,2015-12-12 16:02:36,"[0, 82]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 675707321759039488, 'id_str'...",2141,False,We've got ourselves a battle here. Watch out R...,675707330206547968,dog_rates,6.754971e+17,...,0.0,0.0,NaN,NaN,767,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1862,2015-12-11 16:20:15,"[0, 58]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 675349367813877760, 'id_str'...",4230,False,Yea I lied. Here's more. All 13/10 https://t.c...,675349384339542016,dog_rates,6.749998e+17,...,0.0,0.0,NaN,NaN,2520,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1878,2015-12-10 17:11:09,"[0, 101]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 674999800484368385, 'id_str'...",2417,False,Ok last one of these. I may try to make some m...,674999807681908736,dog_rates,6.747934e+17,...,0.0,0.0,NaN,NaN,1228,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1881,2015-12-10 03:30:58,"[0, 51]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 674793390643482624, 'id_str'...",2679,False,I have found another. 13/10 https://t.co/HwroP...,674793399141146624,dog_rates,6.717299e+17,...,0.0,0.0,NaN,NaN,1217,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1888,2015-12-10 00:54:28,"[0, 89]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 674754014320402432, 'id_str'...",1457,False,Just received another perfect photo of dogs an...,674754018082705410,dog_rates,6.747522e+17,...,0.0,0.0,NaN,NaN,488,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1891,2015-12-10 00:08:50,"[0, 107]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,525,False,Some clarification is required. The dog is sin...,674742531037511680,dog_rates,6.747400e+17,...,NaN,NaN,NaN,NaN,55,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1901,2015-12-09 15:09:55,"[0, 134]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,1006,False,The 13/10 also takes into account this impecca...,674606911342424069,dog_rates,6.744689e+17,...,NaN,NaN,NaN,NaN,113,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
1936,2015-12-07 04:11:02,"[0, 88]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,3274,False,The millennials have spoken and we've decided ...,673716320723169284,dog_rates,6.737159e+17,...,NaN,NaN,NaN,NaN,839,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
2032,2015-12-01 16:37:44,"[0, 76]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 671729900588417024, 'id_str'...",9073,False,I'm just going to leave this one here as well....,671729906628341761,dog_rates,6.715610e+17,...,0.0,0.0,NaN,NaN,4766,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
2034,2015-12-01 04:44:10,"[0, 135]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,963,False,After 22 minutes of careful deliberation this ...,671550332464455680,dog_rates,6.715449e+17,...,NaN,NaN,NaN,NaN,228,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
2145,2015-11-26 01:11:28,"[0, 125]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,551,False,After countless hours of research and hundreds...,669684865554620416,dog_rates,6.693544e+17,...,NaN,NaN,NaN,NaN,98,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
2165,2015-11-25 03:14:30,"[0, 114]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 669353426984296449, 'id_str'...",688,False,This is Tessa. She is also very pleased after ...,669353438988365824,dog_rates,6.678065e+17,...,0.0,0.0,NaN,NaN,279,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."
2294,2015-11-18 20:02:51,"[0, 69]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,87,False,After much debate this dog is being upgraded t...,667070482143944705,dog_rates,6.670655e+17,...,NaN,NaN,NaN,NaN,14,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 4196983835, 'id_str': '4196983835', 'na..."

In [66]:
### check values
tweetclean.in_reply_to_screen_name.value_counts()
### may be dog_rates is a default reply name or thumbs
### drop column

dog_rates          47
markhoppus          2
imgur               1
TheEllenShow        1
s8n                 1
ComplicitOwl        1
roushfenway         1
shibbnbot           1
dhmontgomery        1
bragg6of8           1
RealKentMurphy      1
NonWhiteHat         1
0_kelvin_0          1
xianmcguire         1
mount_alex3         1
Jack_Septic_Eye     1
UNC                 1
docmisterio         1
wane15              1
SkyWilliams         1
NBCSports           1
spaghemily          1
JODYHiGHROLLER      1
jonnysun            1
ABC                 1
ABC7                1
HistoryInPics       1
Marc_IRL            1
serial              1
CommonWhiteGirI     1
LightningHoltt      1
Name: in_reply_to_screen_name, dtype: int64

In [103]:
## droplist2
droplist2 = inslist1.copy()
### use .copy to copy rather than llink
droplist2.append('quoted_status')
droplist2.append('retweeted_status')
droplist2.append('user')
#droplist2 = ['truncated','retweeted','possibly_sensitive_appealable','possibly_sensitive','lang','is_quote_status','favorited']

In [112]:
## drop2 excute
drop_column(tweetclean,droplist2)

---- proceding ----
- drop 14 columns: ['favorited', 'in_reply_to_screen_name', 'in_reply_to_status_id', 'in_reply_to_user_id', 'is_quote_status', 'lang', 'possibly_sensitive', 'possibly_sensitive_appealable', 'quoted_status_id', 'retweeted', 'truncated', 'quoted_status', 'retweeted_status', 'user']
- remain 9 columns
- success : True

#### // check3 - detail cols

In [115]:
# check3
## recheck sample
check_sample(tweetclean)

----checking sample index: 1735

- columns #1 : created_at
['2015-12-23T03:58:25.000000000']

- columns #2 : display_text_range
[list([0, 133])]

- columns #3 : entities
[{'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 679511347441328128, 'id_str': '679511347441328128', 'indices': [110, 133], 'media_url': 'http://pbs.twimg.com/media/CW4b-GUWYAAa8QO.jpg', 'media_url_https': 'https://pbs.twimg.com/media/CW4b-GUWYAAa8QO.jpg', 'url': 'https://t.co/bwuV6FlRxr', 'display_url': 'pic.twitter.com/bwuV6FlRxr', 'expanded_url': 'https://twitter.com/dog_rates/status/679511351870550016/photo/1', 'type': 'photo', 'sizes': {'medium': {'w': 505, 'h': 639, 'resize': 'fit'}, 'large': {'w': 505, 'h': 639, 'resize': 'fit'}, 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'small': {'w': 505, 'h': 639, 'resize': 'fit'}}}]}]

- columns #4 : extended_entities
[{'media': [{'id': 679511347441328128, 'id_str': '679511347441328128', 'indices': [110, 133], 'media_url': 'http://pbs.twimg.com/media/CW4b-GUWYAAa8QO.jpg', 'media_url_https': 'https://pbs.twimg.com/media/CW4b-GUWYAAa8QO.jpg', 'url': 'https://t.co/bwuV6FlRxr', 'display_url': 'pic.twitter.com/bwuV6FlRxr', 'expanded_url': 'https://twitter.com/dog_rates/status/679511351870550016/photo/1', 'type': 'photo', 'sizes': {'medium': {'w': 505, 'h': 639, 'resize': 'fit'}, 'large': {'w': 505, 'h': 639, 'resize': 'fit'}, 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'small': {'w': 505, 'h': 639, 'resize': 'fit'}}}]}]

- columns #5 : favorite_count
[3694]

- columns #6 : full_text
["Say hello to William. He makes fun of others because he's terrified of his own deep-seated insecurities. 7/10 https://t.co/bwuV6FlRxr"]

- columns #7 : id------
[679511351870550016]

- columns #8 : retweet_count
[1454]

- columns #9 : source--
['<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>']
'----checking complete----'

In [117]:
## detlist1
### check dict long columns
detlist1 = ['entities','extended_entities']

In [120]:
## det check
check_detail(tweetclean,detlist1)
### not new info  -> drop

- columns #1 : entities
{'hashtags': [],
 'media': [{'display_url': 'pic.twitter.com/MgUWQ76dJU',
            'expanded_url': 'https://twitter.com/dog_rates/status/892420643555336193/photo/1',
            'id': 892420639486877696,
            'id_str': '892420639486877696',
            'indices': [86, 109],
            'media_url': 'http://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg',
            'media_url_https': 'https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg',
            'sizes': {'large': {'h': 528, 'resize': 'fit', 'w': 540},
                      'medium': {'h': 528, 'resize': 'fit', 'w': 540},
                      'small': {'h': 528, 'resize': 'fit', 'w': 540},
                      'thumb': {'h': 150, 'resize': 'crop', 'w': 150}},
            'type': 'photo',
            'url': 'https://t.co/MgUWQ76dJU'}],
 'symbols': [],
 'urls': [],
 'user_mentions': []}

- columns #2 : extended_entities
{'media': [{'display_url': 'pic.twitter.com/MgUWQ76dJU',
            'expanded_url': 'https://twitter.com/dog_rates/status/892420643555336193/photo/1',
            'id': 892420639486877696,
            'id_str': '892420639486877696',
            'indices': [86, 109],
            'media_url': 'http://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg',
            'media_url_https': 'https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg',
            'sizes': {'large': {'h': 528, 'resize': 'fit', 'w': 540},
                      'medium': {'h': 528, 'resize': 'fit', 'w': 540},
                      'small': {'h': 528, 'resize': 'fit', 'w': 540},
                      'thumb': {'h': 150, 'resize': 'crop', 'w': 150}},
            'type': 'photo',
            'url': 'https://t.co/MgUWQ76dJU'}]}

In [121]:
## droplist3
droplist3 = detlist1.copy()

## drop3 excute
drop_column(tweetclean,droplist3)

---- proceding ----
- drop 2 columns: ['entities', 'extended_entities']
- remain 7 columns
- success : True

In [122]:
tweetclean.columns

Index(['created_at', 'display_text_range', 'favorite_count', 'full_text', 'id',
       'retweet_count', 'source'],
      dtype='object')

#### /review/ quanlity
根据数据删除剩余7列 ['created_at', 'display_text_range', 'favorite_count', 'full_text', 'id',
       'retweet_count', 'source']
- id 为标识列
- created_at 包括时间、日期,可以进行时序分析
- display_text_range 为文字长度
- favorite_count 为点赞数
- full_text 为文字内容
- retweet_count 为回复数
- source 为来源

### / 清洁度
根据质量部分的输出,对于除id列之外的需要进行清洁度的整理
- created_at 包括时间、日期,可以进行时序分析
    - 转换为 datafame 的 datetime 格式
- display_text_range 为文字长度
    - 原格式为 [0-x] x实际为推文长度,需要提取 x
    - 本列为非必须列,可以根据 full_text 得出回复长度
- favorite_count 为点赞数
    - 需要检查格式
- full_text 为文字内容
    - 暂不用处理,后续如果进行nlp的分析需要进行向量化
- retweet_count 为回复数
    - 需要检查格式
- source 为来源
    - 来源为链接,中间为发布信息的设备
    - 需要使用 re 来完成提取
    - 最后输出为分类信息

### / copy df

In [134]:
## df copy for cleaning
tweettidy = tweetclean.copy()
### id should retained for further identity usage
### consider privacy and easy of proceed
### delete in this project
droplist4 = ['id']
drop_column(tweettidy,droplist4)

---- proceding ----
- drop 1 columns: ['id']
- remain 6 columns
- success : True

## 清理

### / missing data

In [135]:
# check missing
tweettidy.notnull().all()
## not any null data -> pass

created_at            True
display_text_range    True
favorite_count        True
full_text             True
retweet_count         True
source                True
dtype: bool

In [138]:
# check describe
tweettidy.describe()
## both count do not have to change type
## value seems ok

       favorite_count  retweet_count
count     2352.000000    2352.000000
mean      8109.198980    3134.932398
std      11980.795669    5237.846296
min          0.000000       0.000000
25%       1417.000000     618.000000
50%       3596.500000    1456.500000
75%      10118.000000    3628.750000
max     132318.000000   79116.000000

In [140]:
# check info
tweettidy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2352 entries, 0 to 2351
Data columns (total 6 columns):
created_at            2352 non-null datetime64[ns]
display_text_range    2352 non-null object
favorite_count        2352 non-null int64
full_text             2352 non-null object
retweet_count         2352 non-null int64
source                2352 non-null object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 110.3+ KB

### / tidy data
#### // type - created_at
define: 将数据转换为时间格式
- solution1 使用 dataframe 的 datatime 格式
- solution2 使用 pytghon datatime 格式、calendar格式

In [141]:
# code - created_at
## convert

In [ ]:
## test

#### // display_text_range
define: 抽取出 text 的长度,存为整数
- solution1 使用 dataframe 的 datatime 格式
- solution2 使用 pytghon datatime 格式、calendar格式

In [ ]:
treatments_clean.hba1c_change = (treatments_clean.hba1c_start - 
                                 treatments_clean.hba1c_end)

##### Test

In [ ]:
treatments_clean.hba1c_change.head()

### 清洁度

#### `patients`  表格中的联系方式一列包括两个变量：手机号和邮箱

##### 定义
使用正则表达式和 pandas 的 `str.extract` 方法，从 *联系方式* 一列提取变量*手机号* 和 *邮箱* 。完成后删除 *联系方式* 一列。

##### 代码

In [ ]:
patients_clean['phone_number'] = patients_clean.contact.str.extract('((?:\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4})', expand=True)
patients_clean['email'] = patients_clean.contact.str.extract('([a-zA-Z][a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.][a-zA-Z]+)', expand=True)
# Note: axis=1 表明我们参考的是一列，而不是一行
patients_clean = patients_clean.drop('contact', axis=1)

##### 测试

In [ ]:
# 确认联系方式一列可以运行
list(patients_clean)

In [ ]:
patients_clean.phone_number.sample(25)

In [ ]:
# 确认没有邮箱以整数开头 (正则表达式不能匹配整数)
patients_clean.email.sort_values().head()

#### `treatments` 表格两列中的三个变量 (治疗、初始剂量和最终剂量)

##### 定义
在 *auralin* 和 *novodra* 两列中加入 *治疗* 和 *剂量* 列 (这时剂量仍然包含初始剂量和最终剂量)。然后使用破折号 ' - ' 把剂量列切分，得到 *初始剂量* 和 *最终剂量* 两列。删除中间使用的 *剂量* 一列。

##### Code

In [ ]:
treatments_clean = pd.melt(treatments_clean, id_vars=['given_name', 'surname', 'hba1c_start', 'hba1c_end', 'hba1c_change'],
                           var_name='treatment', value_name='dose')
treatments_clean = treatments_clean[treatments_clean.dose != "-"]
treatments_clean['dose_start'], treatments_clean['dose_end'] = treatments_clean['dose'].str.split(' - ', 1).str
treatments_clean = treatments_clean.drop('dose', axis=1)

##### Test

In [ ]:
treatments_clean.head()

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

#### 不良反应应是 `treatments` 表格的一部分

##### 定义
将 *不良反应* 一列合并到 `treatments` 表格中，按照 *名* 和 *姓*进行合并。

##### 代码

In [ ]:
treatments_clean = pd.merge(treatments_clean, adverse_reactions_clean,
                            on=['given_name', 'surname'], how='left')

##### Test

In [ ]:
treatments_clean

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

####  `patients` 表格中的姓和名两列复制到 `treatments` 和 `adverse_reactions` 表格中，以及小写形式的姓和名

##### 定义
我们不再需要不良反应表格，所以忽略这部分内容。在 `patients` 表格中，提取病人编号和姓名，然后把这些名字改为小写形式，加入到 `treatments` 表格中。然后删除治疗表格中的姓和名两列 (这样小写形式不再是问题了)。

##### 代码

In [ ]:
id_names = patients_clean[['patient_id', 'given_name', 'surname']]
id_names.given_name = id_names.given_name.str.lower()
id_names.surname = id_names.surname.str.lower()
treatments_clean = pd.merge(treatments_clean, id_names, on=['given_name', 'surname'])
treatments_clean = treatments_clean.drop(['given_name', 'surname'], axis=1)

##### 测试

In [ ]:
# 确认进行了正确融合
treatments_clean

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

In [ ]:
# Patient ID should be the only duplicate column
all_columns = pd.Series(list(patients_clean) + list(treatments_clean))
all_columns[all_columns.duplicated()]

### 质量

#### 邮编是浮点，而不是字符串，有时是四位数

##### 定义
Convert the zip code column's data type from a float to a string 使用 `astype` 把邮件一列的数据类型从浮点转换为字符串，使用字符串分割删除 '.0'。在四位数邮编前面加上 0。 

##### Code

In [ ]:
patients_clean.zip_code = patients_clean.zip_code.astype(str).str[:-2].str.pad(5, fillchar='0')
# 对于上面代码转化后的'0000n'非数字条目，进行再次转化
patients_clean.zip_code = patients_clean.zip_code.replace('0000n', np.nan)

##### 测试

In [ ]:
patients_clean.zip_code.head()

#### Tim Neudorf 的身高是 27 英尺，而不是 72 英尺

##### 定义
在 `patients` 表格中身高为 27 英尺 (仅有一个) 的一行身高，替换为72英尺。

##### Code

In [ ]:
patients_clean.height = patients_clean.height.replace(27, 72)

##### Test

In [ ]:
# 应为空
patients_clean[patients_clean.height == 27]

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

In [ ]:
# 确认完成替换
patients_clean[patients_clean.surname == 'Neudorf']

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

#### 有时使用州的全称，其他用简称

##### 定义
使用函数，将 California (加利福尼亚)、New York (纽约)、Illinois (伊利诺伊)、Florida (佛罗里达) 和 Nebrask (内布拉斯加) 等州的全称转变为简称。

##### 代码

In [ ]:
# 从州的全称映射到简称
state_abbrev = {'California': 'CA',
                'New York': 'NY',
                'Illinois': 'IL',
                'Florida': 'FL',
                'Nebraska': 'NE'}

# 使用的函数
def abbreviate_state(patient):
    if patient['state'] in state_abbrev.keys():
        abbrev = state_abbrev[patient['state']]
        return abbrev
    else:
        return patient['state']
    
patients_clean['state'] = patients_clean.apply(abbreviate_state, axis=1)

##### Test

In [ ]:
patients_clean.state.value_counts()

#### Dsvid Gustafsson

##### Define
在 `patients` 表格中含有名 'Dsvid' 的一行里替换为'David'。

##### 代码

In [ ]:
patients_clean.given_name = patients_clean.given_name.replace('Dsvid', 'David')

##### 测试

In [ ]:
patients_clean[patients_clean.surname == 'Gustafsson']

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

#### 错误的数据类型 (指定性别、州、邮编和出生日期列) 和错误的数据类型 (auralin 和 novodra 列)，以及 Auralin 和 Novodra 初始剂量和最终剂量中的字母 'u'

##### Define
将指定性别和州转化为分类数据类型。上面已经解决了邮编的数据类型。把出生日期转化为 datetime 数据类型。在初始剂量和最终剂量中添加字母 'u'，并把这些列转化为整数数据类型。 

##### 代码

In [ ]:
# 转为分类数据类型
patients_clean.assigned_sex = patients_clean.assigned_sex.astype('category')
patients_clean.state = patients_clean.state.astype('category')

# 转为 datetime 类型
patients_clean.birthdate = pd.to_datetime(patients_clean.birthdate)

# 添加 u 并转为整数类型
treatments_clean.dose_start = treatments_clean.dose_start.str.strip('u').astype(int)
treatments_clean.dose_end = treatments_clean.dose_end.str.strip('u').astype(int)

##### Test

In [ ]:
patients_clean.info()

In [ ]:
treatments_clean.info()

#### 多个手机号格式

##### 定义
增加所有的 " "、 "-"、"(", ")" 和 "+"，存储所有没有格式的数字。如果手机号只有 10 位数，在手机号前添加 1 (我们需要国家编号)。

##### 代码

In [ ]:
patients_clean.phone_number = patients_clean.phone_number.str.replace(r'\D+', '').str.pad(11, fillchar='1')

##### 测试

In [ ]:
patients_clean.phone_number.head()

#### John Doe 的默认数据

##### 定义
从 `patients` 表格中删除不可恢复的 John Doe 记录。

##### 代码

In [ ]:
patients_clean = patients_clean[patients_clean.surname != 'Doe']

##### 测试

In [ ]:
# 应该没有 Doe 记录
patients_clean.surname.value_counts()

In [ ]:
# 应该没有 123 Main Street 记录
patients_clean.address.value_counts()

#### Jakobsen、Gersten、Taylor 多条记录

##### 定义
从 `patients` 表格中删除  Jake Jakobsen、Pat Gersten 和 Sandy Taylor。这些是昵称，不应该出现在 `treatments` 表格中 (删除错误名字可以保证  `patients` 和 `treatments` 表格的一致性问题)。这些是复制后第二次出现。这些是唯一出现的非空值复制地址。

##### 代码

In [ ]:
# 波浪符号表示否： http://pandas.pydata.org/pandas-docs/stable/indexing.html#boolean-indexing
patients_clean = patients_clean[~((patients_clean.address.duplicated()) & patients_clean.address.notnull())]

##### Test

In [ ]:
patients_clean[patients_clean.surname == 'Jakobsen']

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

In [ ]:
patients_clean[patients_clean.surname == 'Gersten']

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

In [ ]:
patients_clean[patients_clean.surname == 'Taylor']

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

#### Zaitseva 体重单位是 kgs，不是 lbs 

##### 定义
使用 [高级索引](https://stackoverflow.com/a/44913631) 把姓是 Zaitseva 的行隔离出来，并把体重单元格中的 kg 改为 lbs。

##### 代码

In [ ]:
weight_kg = patients_clean.weight.sort_values()[210]
mask = patients_clean.surname == 'Zaitseva'
column_name = 'weight'
patients_clean.loc[mask, column_name] = weight_kg * 2.20462

##### 测试

In [ ]:
# 48.8 不应该是最低的
patients_clean.weight.sort_values()

In [ ]:
# bokeh (drop)
## https://github.com/bokeh/bokeh-notebooks
## 工具栏设置 https://www.cnblogs.com/shengyang17/p/9739571.html
## 对比了一下,决定使用 plotly 并且以后扩展 dash

In [260]:
# plotly
## 如果使用账号,可以将图存到网上,也可本地使用
## https://blog.csdn.net/u012897374/article/details/77857980
## https://zhuanlan.zhihu.com/p/32793153
## https://plot.ly/python/getting-started/#jupyter-setup

import plotly.offline as py
from plotly.graph_objs import Scatter, Layout
import plotly.graph_objs as go

py.init_notebook_mode(connected=True)

trace1=go.Scatter(
    x=[1,2],
    y=[1,2]
)
trace2=go.Scatter(
    x=[1,2],
    y=[2,1]
)
py.iplot([trace1, trace2])